22:
- deal_number
- insured
- address
- counterparty
- beneficiary_address
- loadport_locality
- loadport_country
- disport_locality
- disport_country
- vessel
- imo
- date_built
- surveyor_loadport
- surveyor_disport
- subject_matter
- provisional
- weight_metric
- ccy
- basis_of_valuation
- sum_insured
- contract_number
- disport_eta

20:
- deal_number
- insured
- address
- counterparty
- beneficiary_address
- loadport_locality
- loadport_country
- disport_locality
- disport_country
- vessel
- imo
- date_built
- surveyor_loadport
- surveyor_disport
- subject_matter
- provisional
- weight_metric
- ccy
- basis_of_valuation
- sum_insured

16:
- counterparty
- beneficiary_address
- loadport_locality
- loadport_country
- disport_locality
- disport_country
- vessel
- imo
- date_built
- surveyor_loadport
- surveyor_disport
- subject_matter
- provisional
- ccy
- weight_kg
- sum_insured

15:
- deal_number
- insured
- address
- counterparty
- beneficiary_address
- loadport_locality
- loadport_country
- disport_locality
- disport_country
- vessel
- imo
- date_built
- surveyor_loadport
- ccy
- sum_insured

14:
- deal_number
- insured
- address
- counterparty
- beneficiary_address
- loadport_locality
- loadport_country
- disport_locality
- disport_country
- vessel
- imo
- date_built
- ccy
- sum_insured
